numero_entero = 10
print("numero entero:", numero_entero)
numero_entero = 5
print("numero entero:", numero_entero)
numero_entero = 2
print("numero entero:", numero_entero)
numero_flotante = 5.12
print("numero flotante:", numero_flotante)
numero_flotante = 9.12
print("numero flotante:", numero_flotante)
numero_flotante = 1.18
print("numero flotante:", numero_flotante)
cadena = 'la promo'
print("cadena:", cadena)
cadena = 'buen dia'
print("cadena:", cadena)
cadena = 'jejejej'
print("cadena:", cadena)
es_verdadero = True
print("¿es verdadero?", es_verdadero)
es_verdadero = False
print("¿es verdadero?", es_verdadero)
es_verdadero = False
print("¿es verdadero?", es_verdadero)
